- thrift/native.thrift
This means the generated Java classes go into a package `com.theguardian.webview.thrift`.
> Add a java namespace

- thrift/native.thrift
- thrift/webview.thrift
This PR turns the `insertEpics` function from the `Webview` service into a `getEpics` function in the 'Native' interface.
`getEpics` should return a non-empty list of epics to be displayed, or an empty list if no epics should be displayed.
This PR is to support issue #12
> Turn insertEpics into getEpics

- thrift/native.thrift
Reverts guardian/mobile-apps-thrift#15 because it seems to affect the Typescript generated code as well, unfortunately.
This might be a bug in the Typescript Thrift compiler we're using, the spec for `namespace` declarations is here: https://thrift.apache.org/docs/idl#namespace and it looks like this change should only have affected Java generated code.
> Revert "Add a java namespace"

- thrift/native.thrift
Will be used here: https://github.com/guardian/apps-rendering/pull/195/files#diff-de307717ea9472420901e5153c47b1ddR90
We currently only register an epic has been seen when it's been scrolled into the webview viewport. We use something like `signal_device('creative-impression')` in the templates.
> register epic was scrolled into viewport and seen by user

- .github/actions/generate-native-package/native.sh
We renamed https://github.com/guardian/mobile-apps-thrift-swift to https://github.com/guardian/bridget-swift.
> Update iOS package repo

- .github/actions/generate-native-package/Dockerfile
This points to https://github.com/guardian/french-thrift instead of https://github.com/davidfurey/thrift. The Guardian fork contains all the changes that we need that haven't yet been merged into the Apache repo.
> Point to Guardian fork of Thrift

- gen-typescript.sh
- package-lock.json
- package.json
This generates JavaScript files with TypeScript definitions for the bridget APIs. This should allow the APIs to be used outside of apps-rendering in other webviews such as interactive atoms.
TODO:
- rename `gen-typescrpt` to `gen-javascript-typescript`
> generate and publish javascript files

- thrift/native.thrift
This can be removed afterwards, just need to test the process.
> test process with dummy function

- .github/actions/generate-native-package/native.sh
- README.md
- gen-typescript.sh
- thrift/webview.thrift
With the new fontSize solution it looks like we no longer need the native to webView communication.
> remove unused webview thrift file

- thrift/native.thrift
https://github.com/guardian/bridget/issues/37
Would an enum be useful?
```
enum TopicType {
Content,
TagContributor,
TagKeyword,
TagSeries,
TagBlog
FootballTeam,
FootballMatch
}
```
> Add a better display name for users

- thrift/native.thrift
https://github.com/guardian/bridget/issues/40
iOS and Android both show the title in the gallery viewer, so I think it makes sense to pass this additional information.
Follow up apps-rendering change: https://github.com/guardian/apps-rendering/pull/349
> pass article title to native layers

- thrift/native.thrift
https://github.com/guardian/bridget/issues/38
apart from `index` do we need to pass this map of data with every adSlot?
> add targeting param map to AdSlot

- thrift/native.thrift
The webview is already sending floats, Bridget is converting them into ints, that iOS is turning into floats.
We're losing a small bit of precision and needlessly using integers.
> use double for Rect positions

- thrift/native.thrift
Fix for GLA-2121, where images can be shown in the incorrect ratio in the slideshow/lightbox viewer.
apps-rendering and iOS changes required to implement this update.
> add height and width to image struct

- thrift/native.thrift
- By retrieving the user Id from the native layers, we can make a request to the discussion service for things like name, avatar url and badges.
- Adds callbacks that we can hopefully pass through to disucssion-rendering https://github.com/guardian/discussion-rendering/pull/344
> apis to use discussion rendering

- thrift/native.thrift
This PR adds the type `FrictionScreenReason` which is an enum of either values: `hideAds` or `epic`.
The explicit integer values ( ` = 0` and ` = 1`) are not necessary, however it's best to be explicit in these types as order matters in thrift definitions.
> Friction screen reason

- thrift/native.thrift
`launchFrictionScreen` in reality is launching the purchase screen. Renaming this before we go to prod so we're more consistent naming wise.
> Rename friction screen to purchase screen

- package.json
- thrift/native.thrift
Creates a new Analytics service with a single method to send targeting params. Currently the targeting params exist inside the article `<head />` in an `application/json` script that looks like this:
```html
<script id="targeting-params" type="application/json">
{"ct":"article","co":"rebecca-ratcliffe","url":"/world/2021/apr/06/wanted-lists-published-in-myanmar-as-junta-extends-crackdown","su":"4,5","edition":"uk","tn":"news","p":"app","k":"world,south-and-central-asia,myanmar"}
</script>
```
We can use the new method to send these over.
> LIVE-1852:  Analytics service

- README.md
Update main README with a note about where the Android specific files for Bridget are generated.
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Add note about Android files for Bridget

- README.md
- Updates the README with the correct link to the the `apps-rendering` repository
- Removes information in README about Java package publishing. The Java interafaces are compiled locally, without being published to a repository
> docs: update link to apps-rendering repo and info about java package publishing

- .github/workflows/generate-packages.yml
- thrift/trigger-release.txt
- Adds a file in the `thrift/` directory to trigger the release GHA (`.github/workflows/generate-packages.yml`) to run. This action only runs on pushes to `main` with changes in the `thrift/` directory.
- we should be able to specify a `patch` version increase by using the `#patch` tag in the commit message (as in 858a520707f4b2850fdac99a0eb45594fa3dca9c)
- After the patch release has been made, we then need to create a new PR which reverts this change. If we include the `#none` tag in the commit, the revert PR [should not trigger a release](https://github.com/anothrNick/github-tag-action#bumping). We should **not** revert this PR, as that will include a commit with the `#patch` instruction which takes priority over `#none`
- I have bumped the version of `anothrNick/github-tag-action` …
> Trigger a patch release

- README.md
- Fixes link to the generated NPM package `@guardian/bridget`
> Fix README link to NPM package

- thrift/trigger-release.txt
> **Warning**
> When merging this PR, we should include `#none` in the merge commit. This is so the [GitHub Action which manages versioning ](https://github.com/anothrNick/github-tag-action) does **not** bump the version again. [More info on the use of #none](https://github.com/anothrNick/github-tag-action#bumping)
As described in https://github.com/guardian/dotcom-rendering/issues/6196, we have releasted a patch version of Bridget. In order to do so, we had to create a dummy file in the `thrift/` directory. This PR removes that file.
- Removes the dummy file created in guardian/bridget#88
> Remove the file used to trigger a patch release in #88

- .github/workflows/validate-thrift.yml
- README.md
- Adds documentation about the release process and version increments
- Only runs the "Validate Thrift" GitHub Action if files in the `thrift/` directory have changed
> docs: add information about the release process

- thrift/native.thrift
After some discussion, it was decided that the function definition introduced in https://github.com/guardian/bridget/pull/82 should change to return a plain Boolean rather than the `NewsletterSignUpResponse`, which essentially wrapped up a success Bool anyway.
The agreement was that any failures can be passed back by the native layer through this boolean value, rather than by throwing an exception.
Since this is a breaking change, the proposal is to bump the major version number to 2.0
> Return Boolean from Newsletters sign up

- .github/workflows/snyk.yml
The Dotcom team is now maintaining AR.
Paired with @ioannakok @Georges-GNM 
- Move Snyk to upload to Dotcom project
> Move Snyk To Dotcom Project

- README.md
- Adds additional information on why the `generate-swift-package` GitHub Action step might fail
The compiled Bridget library for Swift is released by pushing to the [`bridget-swift`](https://github.com/guardian/bridget-swift) repository's `main` branch. This push requires read/write permissions on the `bridget-swift` repository. The `generate-swift-package` GitHub Action does not automatically have these permissions, so we pass the `ACCESS_TOKEN` repository secret to the action. This token is used to grant access to push to `bridget-swift`.
There is not an organisation-managed access token available, so we must create one and set it for this project. Setting a repository secret requires administrator access to the repository.
> additional info about why the `generate-swift-package` action might fail

- thrift/native.thrift
Extends PR #105 
For the beta roll-out phase of MyGuardian, apps devs need the option to control whether or not MyGuardian features are visibile in Article Webviews.
We will be performing two checks - bridget version compatibility AND a feature flag on the native client envirionment. This is to allow the bridget version on the app builds to be updated, but to not necessarily show MyGuardian features despite this. 
We are thinking of this as a "feature switch". The other option is the add a boolean to the TagService (bool shouldShowFollowTag) but the suggestion was that a decoupled MyGuardian switch would be neater as assuming it would eventually need to be deprecated. 
This environment switche would hang around depite being deprecated in future.
> Add isMyGuardianEnabled feature flag to Environment service

- .github/actions/generate-native-package/native.sh
- .github/workflows/generate-packages.yml
This PR is part of the set of work to automate generation of Bridget models for the Android app. At the moment, the models are manually (and sporadically) updated.
This PR adds support for generating Android specific Bridget models in `bridget-android` when the thrift file is updated.
Key changes:
1. Updated `native.sh` to update [`bridget-android`](https://github.com/guardian/bridget-android/) repo with new generated code.
2. Updated `generate-packages.yml` workflow to execute a job for Android
> **Note**
> This PR depends on https://github.com/guardian/bridget-android/pull/1, so should only be merged/tested after that one has been merged in.
**Other PRs in the set**
1. Replace manually generated code with externally provided JAR in the app repository: …
> Add support for generating Android code when Bridget is updated

- .github/workflows/generate-packages.yml
- .github/workflows/validate-thrift.yml
Part of the Continuous Deployment pipeline for Bridget includes the `generate-packages` action. This action decides the next version of Bridget, and tags the repository. For this reason, the action needs write permissions on the repository.
> Add write permissions to generate-packages action

- .github/actions/generate-native-package/Dockerfile
- .github/actions/validate-thrift/Dockerfile
Keeping things up to date.
This change has been [successfully tested](https://github.com/guardian/bridget/actions/runs/6624957305/job/17994963851?pr=109) in the `validate-thrift` workflow.
> Bump ubuntu in Docker to 22.04

- .github/actions/generate-native-package/action.yml
- .github/actions/generate-native-package/native.sh
- .github/workflows/generate-packages.yml
- .github/workflows/generate-prerelease.yml
- gen-typescript.sh
- Passes which version to release as an argument to the scripts that perform the release, instead of determining the version inside each script. The version is calculated in the GitHub action.
Determining the version in each script is a bit confusing, and tightly couples each script to a specific set of conventions and available tools. By passing the version into the scripts as an input, we remove some of this confusion and centralise it in the GitHub Actions workflows.
- [GitHub prerelease](https://github.com/guardian/bridget/releases/tag/v0.0.0-2024-02-20-VERSION-2)
- [Action run](https://github.com/guardian/bridget/actions/runs/7978363096)
Closes https://github.com/guardian/bridget/issues/119
> Pass version as an argument to release scripts

- .github/workflows/release.yml
- As mentioned in #115, implementing something that only runs on merges to `main` can be tricky! In this case, we should also make sure to only try and create a Release in GitHub if the version has changed. Additionally, the `publish` script needs to be executable. Using `node -e true` is executable, whereas `exit 0` is not!
> Fix changesets release

- .github/workflows/generate-prerelease.yml
- .github/workflows/release.yml
We use GitHub Actions Workflows to deploy releases of Bridget. Part of the release process is pushing tags and branches to `guardian/bridget,` `guardian/bridget-swift` and `guardian/bridget-android`. Pushing to repositories other than `guardian/bridget` require an access token. Previously, this was provided as a fine-grained Personal Access Token tied to an individual account. This is less than ideal, and so instead we have:
- Created a GitHub App and installed it to the `guardian/bridget` repository with read & write access to `guardian/bridget,` `guardian/bridget-swift` and `guardian/bridget-android`
- Updated the release and prerelease workflows to use this app to obtain a token which can be used to authenticate git operations to these repositories.
Paired with @alinaboghiu!
Tested in …
> Authenticate release workflows using a GitHub App

- .changeset/fair-months-collect.md
- .github/actions/generate-native-package/Dockerfile
- .github/actions/validate-thrift/Dockerfile
Compiles Bridget's models with `guardian/french-thrift@0.19.0-gu1`
Part of https://github.com/guardian/bridget/issues/127.
> Compile models with `guardian/french-thrift@0.19.0-gu1`

- .github/workflows/release.yml
Using the token from the GitHub App is [discouraged for this usage](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow#about-github-actions-authentication)!
> Use the GitHub token for changesets

- .changeset/silver-cooks-report.md
- .github/workflows/generate-prerelease.yml
- .github/workflows/release.yml
- Refactors the release workflow to run the typescript, native android and native iOS jobs in parallel. Previously, these were run as one job which meant it was not possible to retry any part without running all the others. This gives us the flexibility to e.g retry the android release if it fails for some reason
- Refactors the native release to a matrix job, as the configuration is essentially unchanged between iOS and Android
The previous release failed for iOS and Android, but succeeded for NPM. However, due to the workflow design, we can't retry the iOS and Android parts independently. The NPM step now fails because that version has already been released, and so the rest of the workflow does not run.
As usual, testing the main release is tricky as it requires a merge to `main`. …
> Refactor releases to run tasks in parallel

- .github/workflows/release.yml
Adds `changesets_release_pr` and `version_check` to the final job's `needs` array, so they can be referenced in the condition that determines whether the job should run.
> Fix syntax error in release workflow

- .github/workflows/release.yml
- Runs `actions/checkout` to check out the repository before trying to create the release, otherwise this step [fails](https://github.com/guardian/bridget/actions/runs/8252544867/job/22572480751)
> Fix "create release" step in release workflow

- .github/workflows/generate-prerelease.yml
The prerelease jobs should not run for regular releases.
> Do not run native prerelease job for non prereleases

- .changeset/quiet-dolls-fold.md
- .changeset/thirty-grapes-repair.md
- thrift/native.thrift
This change:
- Add `signIn` methods to `User` service. DCR can use this method to sign in or register users in-article. This will be used in the discussion app. 
- Add `isSignedIn` method to `User` service. DCR can use these methods to decide what action to perform for certain events (like a user recommending a comment).
When a user interacts with the UI, they want to see updates in the UI. However, if the interaction requires the user to sign in first (like recommending a comment), the Bridget callback channel might time out so we can’t update the UI. The current timeout is 30 seconds. 
~~To get around this, the web view should initiate the sign in flow when the user performs an authenticated action. Once the user is signed in, DCR/the user can retry the authenticated action.~~  To get …
> Add `isSignedIn` and `signIn` methods to `User` service

- .github/workflows/release.yml
We've gone a little off-piste with Changesets because we don't use the `npx changeset ...` commands to actually perform the release, because we're doing more than Changesets is built to handle. But we still want it to manage tagging and creating a GitHub Release for us! This PR fixes (hopefully..) the final remaining issues.
This change:
- Adds a step to tag the repository. This would normally be done by calling `npm version` within the Changesets action. However, we manage the NPM release process in a separate job, and so the tag is lost
- "Tricks" the Changesets action into creating a release in GitHub for us by outputting `"New tag:"` in the `publish` command. The changesets action [looks out](https://github.com/changesets/action/blob/main/src/run.ts#L176) for this string in the output …
> Fix tags and releases

- .changeset/tasty-dolls-protect.md
- thrift/native.thrift
The previous stub was unused. This adds relevant types and signatures for the `recommend` method.
This PR is based off commits in #111. This change adds `recommend` by itself so that it can be implemented soon by Android and iOS.
We can release the remaining Discussion methods in another Bridget version, so the platforms can implement them when ready. This will enable us to render more articles with discussion using DCAR, more quickly.
> Add `recommend` to Discussion service

- .changeset/eleven-pumpkins-hide.md
- thrift/native.thrift
Updates the return type of signIn from void to boolean. This change was suggested by @ddramowicz as a means of keeping code consistent.
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Return a boolean when users sign in

- thrift/native.thrift
The preview and report abuse endpoints are unauthenticated so we can make requests directly in DCR.
> Remove unused `reportAbuse` and `preview` methods

- .github/workflows/validate-thrift.yml
Fixup of #155, [which failed](https://github.com/guardian/bridget/actions/runs/8735698387)
> Fix actions versions syntax

- .changeset/silver-lemons-look.md
- thrift/native.thrift
Add `sendVideoEvent` and `fullscreen` methods to `Videos` service
The `sendVideoEvent` method is required to send video events from webviews to the native layer so that they can be forwarded to Ophan. Webviews do not have access to the Ophan page view id and the native layer will also handle offline mode and batching of requests.
The `fullscreen` method is required for Android as the web YouTube player performs a no-op for fullscreen on Android. We therefore need to instruct the native layer to resize the player into a fullscreen view.
> Add `sendVideoEvent` and `fullscreen` methods to `Videos` service

- .changeset/cyan-months-battle.md
- package-lock.json
- thrift/native.thrift
This PR adds a new service for `Interaction` which includes function `disableArticleSwipe` which notifies the native layer to disable the article swipe feature
We've done a pre-release `v0.0.0-2024-11-18-snapshot-1` to be able to test this in the app. So the PR is pending until it's tested in the apps.
> Add Service Interaction and disableArticleSwipe function

- .changeset/modern-beers-heal.md
- .github/actions/generate-native-package/Dockerfile
- .github/actions/validate-thrift/Dockerfile
This is one of the necessary stages in decommissioning french-thrift, since we have ascertained [here](https://docs.google.com/document/d/1JBGej-2Adn3UrzRMNSlGYn5vWA3Gu4oD4b1ZtyPfWXU/edit?tab=t.0) that it is no longer needed. The full list of steps required to complete this process is documented [here](https://theguardian.atlassian.net/browse/LIVE-7287).
This PR updates the Dockerfiles (used to describe the environment needed to auto-generate the Swift Package) to point to the latest version of Apache Thrift instead of French Thrift.
When all the related PRs are in the right state, we'll need to create a new release of Bridget that we can then use in the iOS repo. We'll then do a smoke test of the app to verify that everything is working as expected.
> Update Dockerfiles to point to Apache Thrift

- .changeset/modern-beers-heal.md
- .github/actions/generate-native-package/Dockerfile
- .github/actions/validate-thrift/Dockerfile
Reverts guardian/bridget#175
After I merged guardian/bridget#175, the [validate-thrift](https://github.com/guardian/bridget/actions/runs/12141551063) GitHub Action in this repo failed. A bit of digging led me to [this](https://github.com/apache/thrift/pull/1997) closed PR in the Apache Thrift repo by David Furey from March 2020. 
From what I can see, these changes never got merged into Apache Thrift, but were made in the French Thrift repo (as [commits](https://github.com/apache/thrift/compare/master...guardian:french-thrift:mobile-apps) straight to master, rather than as PRs), so we can't just do a straight swap of French Thrift for Apache Thrift. 
I'm reverting this PR for now while I consider the best next steps, which might be to resubmit the …
> Revert "Update Dockerfiles to point to Apache Thrift"

- .changeset/slimy-actors-draw.md
- .github/actions/generate-native-package/Dockerfile
- .github/actions/validate-thrift/Dockerfile
In https://github.com/guardian/thrift-swift/pull/10, we update guardian/thrift-swift to point to the latest version of french-thrift. 
This PR updates the Dockerfiles (used to describe the environment needed to auto-generate the Swift Package) to point to the latest version of french-thrift.
When all the related PRs are in the right state, we'll need to create a new release of Bridget that we can then use in the iOS repo. We'll then do a smoke test of the app to verify that everything is working as expected.
> Update to french-thrift@v0.21.0-gu1

- .changeset/slimy-actors-draw.md
- .github/actions/generate-native-package/Dockerfile
- .github/actions/validate-thrift/Dockerfile
Reverts guardian/bridget#179
CI has been failing on Bridget since guardian/bridget#179 was merged, so I'm reverting that PR here pending further investigation.
> Revert "Update to french-thrift@v0.21.0-gu1"

- .changeset/loud-penguins-taste.md
- .github/actions/generate-native-package/Dockerfile
- .github/actions/validate-thrift/Dockerfile
This PR updates the Dockerfiles (used to describe the environment needed to auto-generate the Swift Package) to point to the [latest version](https://github.com/guardian/french-thrift/releases/tag/v0.21.0-gu2) of french-thrift.
> Update to french-thrift@v0.21.0-gu2

- .changeset/odd-flies-prove.md
Update bridget version after horizontal scroll release in prod
This version update doesn't have any changes in bridget. The Bridget version 8.1.0 that introduced Interaction service hadn't been fully implemented in the native app. Now the implementation is completed in the android, so we are updating bridget in order to rely on this version in MAPI for articles that need the Interaction service.
**TODO:**
After this version is released, we will need to update the min required bridget version in this DCR pull request https://github.com/guardian/android-news-app/pull/10921 to the new bridget version. 
Also, for releasing liveblog to PROD, we would need to use this bridget version in MAPI.
> upgrade bridget version after horizontal scroll release in prod

- .changeset/good-emus-jog.md
- package-lock.json
Update Bridget Version to Set Minimum Requirement for Liveblogs
This version update introduces no changes to Bridget itself. Its sole purpose is to establish a minimum Bridget version requirement for DCAR liveblogs. This is necessary because Android recently fixed an ad-related bug, allowing DCAR liveblogs to be released in production.
> update bridget version without any change
