guardian/bridget

- README.md
Document the process of adding a new function
> Adding a new function instructions

- thrift/native.thrift
> update ad positions

- .github/actions/generate-native-package/native.sh
This is an updated version of #4 that uses the new "bridget" naming.
> Use async_servers option

- .github/actions/generate-native-package/Dockerfile
This brings in our latest changes to the Swift generator and library.
> Update Thrift version

- thrift/native.thrift
We'd like to push a new build through to test the Swift updates.
> Add dummy function to trigger build

- thrift/native.thrift
> Revert "Add dummy function to trigger build"

- gen-typescript.sh
- thrift/native.thrift
- Publish to `@guardian/bridget`
> Publish to @guardian/bridget

- thrift/native.thrift
> Revert "Update native.thrift"

- thrift/native.thrift
> Revert "Revert "Update native.thrift""

- thrift/native.thrift
This will pass media atom data to the native layers for them to insert videos.
> Insert video API

- thrift/native.thrift
Adds the ability to query whether a user has read an article or list of articles before
> Has seen article

- .github/actions/generate-native-package/native.sh
- .github/workflows/generate-packages.yml
- README.md
Requires an update to bridget-swift repo
> rename references to master branch

- thrift/native.thrift
Adds a new api for checking the status of the user being opted into CCPA to be used by apps rendering to render the appropriate links in the Footer component.
> added ccpaopt in definition

- package.json
- thrift/native.thrift
Got the type and parameter in the wrong order so the packages wouldn't build and deploy.
> correct thrift syntax

- thrift/native.thrift
Reorder discussion service API
> Reorder discussion service

- package.json
- thrift/native.thrift
- Creates the Navigation service
- adds two methods `openPrivacySettings` and `openPrivacyPolicy`
> Navigation service and NavigationLink

- package.json
- thrift/native.thrift
[JIRA ticket](https://theguardian.atlassian.net/browse/LIVE-2517)
Send `isSquare` flag with the `AdSlot` from AR.
> LIVE-2517: Send isSquare flag with AdSlot

- thrift/native.thrift
No content change - just making comment readable on smaller screens by wrapping at 100 char
> Wrap comment to 100c line length

- thrift/native.thrift
Adds a Tag Service  and EnviromentService.isMyGuardianEnabled flag to the bridget library
This will be used to follow contributor tags in MyGuardian, separate to turning Contributor notifications on/off on device. 
The Tag Service has been named agnostically in case is becomes de-linked from MyGuardian in future. 
We will be releasing a snapshot version for testing purposes. 
Question: 
It is unclear to me how users on older App versions using older bridget versions will see the new Follow from Article options - we can either:
Option A/ DON'T show the Follow Tag option on webviews if App version doesn not have MyG? - possibly use bridget version to determine this or do we need an extra field in the model?
Option B/ ALWAYS show the Follow Tag option on Article webviews and use this to …
> Add Tag Service and EnviromentService.isMyGuardianEnabled flag to model

- package.json
> Set `package.json` version to `2.7.0`

- .changeset/silver-cooks-report.md
- CHANGELOG.md
- package.json
> Revert "Version Packages"

- .changeset/khaki-pens-warn.md
- thrift/native.thrift
Adds the remaining discussion methods required to complete the implementation of discussion in DCAR. 
Taken from https://github.com/guardian/bridget/pull/111.
> Add remaining discussion methods

- .changeset/gentle-timers-sort.md
- thrift/native.thrift
Let DCR do the JSON parsing, as it handles it for web already.
Simpler code
We need this to be a major change
> Opaque JSON string from Discussion service response

- .github/workflows/validate-thrift.yml
See title: “Pin `actions/checkout` to v4”
Succesful workflows!
This is the recommended approach from Github
> We strongly recommend that you include the version
> of the action you are using by specifying a Git ref, SHA,
> or Docker tag. If you don't specify a version, it could break
> your workflows or cause unexpected behavior when
> the action owner publishes an update.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
-   [ ] [Colour contrast …
> Pin `actions/checkout` to v4

- thrift/native.thrift
> Add discussion flow link

- .changeset/hip-adults-smoke.md
- thrift/native.thrift
Copy sendTargetingParams method from the analytics to the commercial service
as requested by @EnochHankombo92
>  Copy sendTargetingParams method from the analytics to the commercial service

- .changeset/ten-schools-join.md
Update bridget patch version to re-publish bridget-android
This version update doesn't have any changes in bridget.It's only purpose is to re-publish the bridget-android kotlin library with new thrift version. 
After releasing this version, we will look for a new bridget-android release in here: https://github.com/guardian/bridget-android/actions/workflows/bridget_update.yml
> update bridget patch version

- .changeset/dark-lemons-fail.md
This adds a changeset to include the changes for listen to article 
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Add a changeset 

- .changeset/social-regions-post.md
- thrift/native.thrift
We have decided not to go with hiding behind a feature switch, as we can control the visibility of the button by calling isAvailable() and setting that to false instead. 
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> Remove the isListenToArticleEnabled flag
